name: "Biome analysis"

on:
  push:

jobs:
  Biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24
      - name: Run npm install
        run: npm install
      - name: Run Biome
        run: npm run lint:biome || true
