name: "Biome analysis"

on:
  push:

jobs:
  Biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
      - name: Run npm install
        run: npm install
      - name: Run Biome
        run: npm run lint:biome || true
